---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-01-18 - 13:13:16 +0000
  labels:
    app.kubernetes.io/name: benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: benchmark-client
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9090
  selector:
    app.kubernetes.io/name: benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-01-18 - 13:13:16 +0000
  labels:
    app.kubernetes.io/name: benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: benchmark-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark-client
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-01-18 - 13:13:16 +0000
      labels:
        app.kubernetes.io/name: benchmark-client
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mrigankapaul/benchmark-client:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: benchmark-client
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
